# Generated by Django 5.1 on 2024-11-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('ID_Productos', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Descripcion', models.CharField(max_length=100)),
                ('Precio', models.CharField(max_length=100)),
                ('Cantidad', models.CharField(max_length=15)),
                ('Categoria', models.CharField(max_length=100)),
                ('Fecha_añadido', models.DateField()),
            ],
        ),
    ]
